"""Helpers for generating C6678-oriented source modules."""

from __future__ import annotations

from string import Template
from typing import Any

import tvm
import tvm.runtime._ffi_api
from tvm.target import Target


_SUPPORTED_DTYPES: dict[str, dict[str, Any]] = {
    "float32": {
        "prefix": "fp",
        "c_type": "float",
        "acc_type": "float",
        "block_size": 256,
        "activation_zero": "0.0f",
        "activation_six": "6.0f",
    },
    "float64": {
        "prefix": "dp",
        "c_type": "double",
        "acc_type": "double",
        "block_size": 128,
        "activation_zero": "0.0",
        "activation_six": "6.0",
    },
    "int8": {
        "prefix": "i8",
        "c_type": "int8_t",
        "acc_type": "int32_t",
        "block_size": 128,
        "activation_zero": "0",
        "activation_six": "6",
    },
    "int16": {
        "prefix": "i16",
        "c_type": "int16_t",
        "acc_type": "int32_t",
        "block_size": 128,
        "activation_zero": "0",
        "activation_six": "6",
    },
    "int32": {
        "prefix": "i32",
        "c_type": "int32_t",
        "acc_type": "int64_t",
        "block_size": 128,
        "activation_zero": "0",
        "activation_six": "6",
    },
}

_SCOPE_TO_ENUM = {"ddr": 0, "l2": 1, "smc": 2}
_ACTIVATION_TO_ENUM = {"none": 0, "relu": 1, "relu6": 2}


def _as_target(target: str | Target) -> Target:
    target = Target(target)
    if target.kind.name != "c6678":
        raise ValueError(f"Expected a c6678 target, but got {target.kind.name}")
    return target


def _normalize_scope(name: str, value: str) -> str:
    normalized = value.lower()
    if normalized not in _SCOPE_TO_ENUM:
        raise ValueError(f"Unsupported {name}: {value}")
    return normalized


def _normalize_activation(activation: str) -> str:
    normalized = activation.lower()
    if normalized not in _ACTIVATION_TO_ENUM:
        raise ValueError(f"Unsupported activation: {activation}")
    return normalized


def _pick_int(target: Target, explicit: int | None, attr_name: str, default: int) -> int:
    if explicit is not None:
        return int(explicit)
    if attr_name in target.attrs:
        return int(target.attrs[attr_name])
    return default


def _select_operator_variant(a_scope: str, b_scope: str, c_scope: str) -> str:
    if a_scope == "l2" and b_scope == "l2" and c_scope == "l2":
        return "p"
    return "s"


def _variant_enabled(selected_variant: str, candidate_variant: str) -> int:
    return 1 if selected_variant == candidate_variant else 0


def _build_source(
    *,
    target: Target,
    dtype: str,
    M: int,
    N: int,
    K: int,
    transpose_a: bool,
    transpose_b: bool,
    activation: str,
    bias_broadcast: bool,
    a_scope: str,
    b_scope: str,
    c_scope: str,
    use_multicore: bool,
    core_mask: int,
    core_num: int,
    block_size: int,
    l2_size: int,
    smc_size: int,
    dma_align_bytes: int,
    dma_max_transfer: int,
    vector_bytes: int,
    selected_variant: str,
) -> str:
    dtype_info = _SUPPORTED_DTYPES[dtype]
    template = Template(
        r'''// Generated by tvm.contrib.c6678.build_matmul_module
// target: $target
// dtype: $dtype
// shape: M=$M N=$N K=$K
// scopes: A=$a_scope B=$b_scope C=$c_scope
// selected_variant: $selected_variant
// multicore: $use_multicore core_mask=$core_mask core_num=$core_num
// hardware: l2_size=$l2_size smc_size=$smc_size dma_align_bytes=$dma_align_bytes dma_max_transfer=$dma_max_transfer vector_bytes=$vector_bytes

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "DMA.h"
#include "M6678E_PSC.h"
#include "initial.h"

#ifndef LL2_A_BASE
#define LL2_A_BASE 0
#endif

#ifndef LL2_B_BASE
#define LL2_B_BASE 0
#endif

#ifndef LL2_C_BASE
#define LL2_C_BASE 0
#endif

#ifndef COREID
#define COREID DNUM
#endif

extern int GetLogicCoreId(int core_mask, int core_id);
extern int GetCoreNum(int core_mask);
extern void C6678E_SyncN(int core_num, int logic_core_id);
extern void dma_trans(void *src, void *dst, int size);

enum {
  ACTIVATION_NONE = 0,
  ACTIVATION_RELU = 1,
  ACTIVATION_RELU6 = 2
};

enum {
  C6678_SCOPE_DDR = 0,
  C6678_SCOPE_L2 = 1,
  C6678_SCOPE_SMC = 2
};

typedef struct {
  int M;
  int N;
  int K;
  int transpose_a;
  int transpose_b;
  int activation_type;
  int bias_broadcast;
  int a_scope;
  int b_scope;
  int c_scope;
  int block_size;
} C6678MatmulConfig;

static const C6678MatmulConfig kDefaultMatmulConfig = {
  $M,
  $N,
  $K,
  $transpose_a,
  $transpose_b,
  $activation_type,
  $bias_broadcast,
  $a_scope_enum,
  $b_scope_enum,
  $c_scope_enum,
  $block_size
};

static inline $c_type apply_activation_none($c_type value) { return value; }

static inline $c_type apply_activation_relu($c_type value) {
  return (value > ($c_type)$activation_zero) ? value : ($c_type)$activation_zero;
}

static inline $c_type apply_activation_relu6($c_type value) {
  if (value < ($c_type)$activation_zero) {
    return ($c_type)$activation_zero;
  }
  if (value > ($c_type)$activation_six) {
    return ($c_type)$activation_six;
  }
  return value;
}

static inline $c_type apply_activation(int activation_type, $c_type value) {
  switch (activation_type) {
    case ACTIVATION_RELU:
      return apply_activation_relu(value);
    case ACTIVATION_RELU6:
      return apply_activation_relu6(value);
    case ACTIVATION_NONE:
    default:
      return apply_activation_none(value);
  }
}

static void dma_trans_2d(void *src, void *dst, int acnt, int bcnt, int src_stride, int dst_stride) {
  int row;
  char *src_base = (char *)src;
  char *dst_base = (char *)dst;
  if (acnt <= 0 || bcnt <= 0) {
    return;
  }
  for (row = 0; row < bcnt; ++row) {
    dma_trans(src_base + row * src_stride, dst_base + row * dst_stride, acnt);
  }
}

static void copy_2d_by_scope(const void *src, void *dst, int acnt, int bcnt, int src_stride,
                             int dst_stride, int src_scope, int dst_scope) {
  int row;
  const char *src_base = (const char *)src;
  char *dst_base = (char *)dst;
  if (src_scope == C6678_SCOPE_L2 && dst_scope == C6678_SCOPE_L2) {
    for (row = 0; row < bcnt; ++row) {
      memcpy(dst_base + row * dst_stride, src_base + row * src_stride, acnt);
    }
    return;
  }
  dma_trans_2d((void *)src, dst, acnt, bcnt, src_stride, dst_stride);
}

static void load_row_major_tile(const void *src_base, void *dst, int row0, int col0, int rows,
                                int cols, int src_ld, int elem_size, int src_scope) {
  const char *src = (const char *)src_base + ((row0 * src_ld + col0) * elem_size);
  copy_2d_by_scope(src, dst, cols * elem_size, rows, src_ld * elem_size, cols * elem_size,
                   src_scope, C6678_SCOPE_L2);
}

static void load_transposed_tile(const void *src_base, void *dst, int row0, int col0, int rows,
                                 int cols, int src_ld, int elem_size, int src_scope) {
  int src_row;
  const char *src = (const char *)src_base + ((col0 * src_ld + row0) * elem_size);
  char *dst_base = (char *)dst;
  for (src_row = 0; src_row < cols; ++src_row) {
    copy_2d_by_scope(src + src_row * src_ld * elem_size, dst_base + src_row * elem_size, elem_size,
                     rows, elem_size, cols * elem_size, src_scope, C6678_SCOPE_L2);
  }
}

static void store_row_major_tile(const void *src, void *dst_base, int row0, int col0, int rows,
                                 int cols, int dst_ld, int elem_size, int dst_scope) {
  char *dst = (char *)dst_base + ((row0 * dst_ld + col0) * elem_size);
  copy_2d_by_scope(src, dst, cols * elem_size, rows, cols * elem_size, dst_ld * elem_size,
                   C6678_SCOPE_L2, dst_scope);
}

#define MATMUL_A_VAL(ptr, row, col, M, K, transpose_a) \
  ((ptr)[(transpose_a) ? ((col) * (M) + (row)) : ((row) * (K) + (col))])

#define MATMUL_B_VAL(ptr, row, col, K, N, transpose_b) \
  ((ptr)[(transpose_b) ? ((col) * (K) + (row)) : ((row) * (N) + (col))])

static void ${prefix}_matmul_block_kernel($c_type *A, $c_type *B, $c_type *C, int M, int N, int K,
                                          int transpose_a, int transpose_b) {
  int i;
  int j;
  int k;
  for (i = 0; i < M; ++i) {
    for (j = 0; j < N; ++j) {
      $acc_type sum = ($acc_type)0;
      for (k = 0; k < K; ++k) {
        sum += ($acc_type)MATMUL_A_VAL(A, i, k, M, K, transpose_a) *
               ($acc_type)MATMUL_B_VAL(B, k, j, K, N, transpose_b);
      }
      C[i * N + j] = ($c_type)(C[i * N + j] + ($c_type)sum);
    }
  }
}

#if $emit_p_variant
static void ${prefix}_matmul_fusion_p_impl($c_type *A, $c_type *B, $c_type *C, $c_type *bias,
                                           const C6678MatmulConfig *cfg) {
  int i;
  int j;
  int k;
  for (i = 0; i < cfg->M; ++i) {
    for (j = 0; j < cfg->N; ++j) {
      $acc_type sum = ($acc_type)0;
      for (k = 0; k < cfg->K; ++k) {
        sum += ($acc_type)MATMUL_A_VAL(A, i, k, cfg->M, cfg->K, cfg->transpose_a) *
               ($acc_type)MATMUL_B_VAL(B, k, j, cfg->K, cfg->N, cfg->transpose_b);
      }
      $c_type value = ($c_type)sum;
      if (bias != NULL) {
        value = ($c_type)(value + (cfg->bias_broadcast ? bias[j] : bias[i * cfg->N + j]));
      }
      C[i * cfg->N + j] = apply_activation(cfg->activation_type, value);
    }
  }
}
#endif

#if $emit_s_variant
static void ${prefix}_matmul_fusion_s_impl($c_type *A, $c_type *B, $c_type *C, $c_type *bias,
                                           const C6678MatmulConfig *cfg, int core_mask) {
  int core_num = GetCoreNum(core_mask);
  int core_id = GetLogicCoreId(core_mask, DNUM);
  int rows_per_core;
  int start_row;
  int end_row;
  int i;
  int j;
  int k;
  $c_type *ll2_A;
  $c_type *ll2_B;
  $c_type *ll2_C;
  int a_src_ld = cfg->transpose_a ? cfg->M : cfg->K;
  int b_src_ld = cfg->transpose_b ? cfg->K : cfg->N;

  if (core_num <= 0 || core_id < 0) {
    return;
  }

  rows_per_core = cfg->M / core_num;
  start_row = core_id * rows_per_core;
  end_row = (core_id == core_num - 1) ? cfg->M : (start_row + rows_per_core);

  ll2_A = ($c_type *)LL2_A_BASE;
  ll2_B = ($c_type *)LL2_B_BASE;
  ll2_C = ($c_type *)LL2_C_BASE;

  for (i = start_row; i < end_row; i += cfg->block_size) {
    int current_M = (i + cfg->block_size > end_row) ? (end_row - i) : cfg->block_size;
    for (j = 0; j < cfg->N; j += cfg->block_size) {
      int current_N = (j + cfg->block_size > cfg->N) ? (cfg->N - j) : cfg->block_size;
      memset(ll2_C, 0, current_M * current_N * (int)sizeof($c_type));
      for (k = 0; k < cfg->K; k += cfg->block_size) {
        int current_K = (k + cfg->block_size > cfg->K) ? (cfg->K - k) : cfg->block_size;
        if (cfg->transpose_a) {
          load_transposed_tile(A, ll2_A, i, k, current_M, current_K, a_src_ld, (int)sizeof($c_type),
                               cfg->a_scope);
        } else {
          load_row_major_tile(A, ll2_A, i, k, current_M, current_K, a_src_ld, (int)sizeof($c_type),
                              cfg->a_scope);
        }
        if (cfg->transpose_b) {
          load_transposed_tile(B, ll2_B, k, j, current_K, current_N, b_src_ld, (int)sizeof($c_type),
                               cfg->b_scope);
        } else {
          load_row_major_tile(B, ll2_B, k, j, current_K, current_N, b_src_ld, (int)sizeof($c_type),
                              cfg->b_scope);
        }
        ${prefix}_matmul_block_kernel(ll2_A, ll2_B, ll2_C, current_M, current_N, current_K, 0, 0);
      }
      for (k = 0; k < current_M; ++k) {
        int col;
        for (col = 0; col < current_N; ++col) {
          int bias_index = cfg->bias_broadcast ? (j + col) : ((i + k) * cfg->N + j + col);
          $c_type value = ll2_C[k * current_N + col];
          if (bias != NULL) {
            value = ($c_type)(value + bias[bias_index]);
          }
          ll2_C[k * current_N + col] = apply_activation(cfg->activation_type, value);
        }
      }
      store_row_major_tile(ll2_C, C, i, j, current_M, current_N, cfg->N, (int)sizeof($c_type),
                           cfg->c_scope);
    }
  }

  C6678E_SyncN(core_num, core_id);
}
#endif

void ${selected_function_name}($c_type *A, $c_type *B, $c_type *C, $c_type *bias, int core_mask) {
  if ($selected_variant_is_s) {
    ${prefix}_matmul_fusion_s_impl(A, B, C, bias, &kDefaultMatmulConfig, core_mask);
  } else {
    (void)core_mask;
    ${prefix}_matmul_fusion_p_impl(A, B, C, bias, &kDefaultMatmulConfig);
  }
}
'''
    )
    return template.substitute(
        target=str(target),
        dtype=dtype,
        M=M,
        N=N,
        K=K,
        a_scope=a_scope,
        b_scope=b_scope,
        c_scope=c_scope,
        selected_variant=selected_variant,
        use_multicore="true" if use_multicore else "false",
        core_mask=core_mask,
        core_num=core_num,
        l2_size=l2_size,
        smc_size=smc_size,
        dma_align_bytes=dma_align_bytes,
        dma_max_transfer=dma_max_transfer,
        vector_bytes=vector_bytes,
        c_type=dtype_info["c_type"],
        acc_type=dtype_info["acc_type"],
        prefix=dtype_info["prefix"],
        activation_zero=dtype_info["activation_zero"],
        activation_six=dtype_info["activation_six"],
        transpose_a=int(transpose_a),
        transpose_b=int(transpose_b),
        activation_type=_ACTIVATION_TO_ENUM[activation],
        bias_broadcast=int(bias_broadcast),
        a_scope_enum=_SCOPE_TO_ENUM[a_scope],
        b_scope_enum=_SCOPE_TO_ENUM[b_scope],
        c_scope_enum=_SCOPE_TO_ENUM[c_scope],
        block_size=block_size,
        selected_function_name=f"{dtype_info['prefix']}_matmul_fusion_{selected_variant}",
        selected_variant_is_s="1" if selected_variant == "s" else "0",
        emit_p_variant=_variant_enabled(selected_variant, "p"),
        emit_s_variant=_variant_enabled(selected_variant, "s"),
    )


def build_matmul_module(
    *,
    M: int,
    N: int,
    K: int,
    dtype: str = "float32",
    target: str | Target = "c6678",
    transpose_a: bool = False,
    transpose_b: bool = False,
    activation: str = "none",
    bias_broadcast: bool = True,
    a_scope: str = "ddr",
    b_scope: str = "ddr",
    c_scope: str = "ddr",
    use_multicore: bool = True,
    core_mask: int = 0xFF,
    block_size: int | None = None,
    core_num: int | None = None,
    l2_size: int | None = None,
    smc_size: int | None = None,
    dma_align_bytes: int | None = None,
    dma_max_transfer: int | None = None,
    vector_bytes: int | None = None,
):
    """Build a CSourceModule for the C6678 matmul MVP path."""

    if dtype not in _SUPPORTED_DTYPES:
        raise ValueError(f"Unsupported dtype: {dtype}")

    target = _as_target(target)
    activation = _normalize_activation(activation)
    a_scope = _normalize_scope("a_scope", a_scope)
    b_scope = _normalize_scope("b_scope", b_scope)
    c_scope = _normalize_scope("c_scope", c_scope)

    block_size = int(block_size or _SUPPORTED_DTYPES[dtype]["block_size"])
    core_num = _pick_int(target, core_num, "core_num", 8)
    l2_size = _pick_int(target, l2_size, "l2_size", 512 * 1024)
    smc_size = _pick_int(target, smc_size, "smc_size", 2 * 1024 * 1024)
    dma_align_bytes = _pick_int(target, dma_align_bytes, "dma_align_bytes", 64)
    dma_max_transfer = _pick_int(target, dma_max_transfer, "dma_max_transfer", 0x7FFF)
    vector_bytes = _pick_int(target, vector_bytes, "vector_bytes", 32)
    selected_variant = _select_operator_variant(a_scope, b_scope, c_scope)

    source = _build_source(
        target=target,
        dtype=dtype,
        M=int(M),
        N=int(N),
        K=int(K),
        transpose_a=bool(transpose_a),
        transpose_b=bool(transpose_b),
        activation=activation,
        bias_broadcast=bool(bias_broadcast),
        a_scope=a_scope,
        b_scope=b_scope,
        c_scope=c_scope,
        use_multicore=bool(use_multicore),
        core_mask=int(core_mask),
        core_num=core_num,
        block_size=block_size,
        l2_size=l2_size,
        smc_size=smc_size,
        dma_align_bytes=dma_align_bytes,
        dma_max_transfer=dma_max_transfer,
        vector_bytes=vector_bytes,
        selected_variant=selected_variant,
    )

    prefix = _SUPPORTED_DTYPES[dtype]["prefix"]
    function_names = [f"{prefix}_matmul_fusion_{selected_variant}"]
    return tvm.runtime._ffi_api.CSourceModuleCreate(source, "c6678", function_names, None)


def build_matmul_source(**kwargs) -> str:
    """Generate the source string for the C6678 matmul MVP path."""

    return build_matmul_module(**kwargs).inspect_source("c6678")
