// Generated by tvm.contrib.c6678.build_matmul_module
// target: {"kind":"c6678","tag":"","keys":["cpu"]}
// dtype: float32
// shape: M=256 N=256 K=256
// scopes: A=ddr B=ddr C=ddr
// multicore: true core_mask=255 core_num=8
// hardware: l2_size=524288 smc_size=2097152 dma_align_bytes=64 dma_max_transfer=32767 vector_bytes=32

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "DMA.h"
#include "M6678E_PSC.h"
#include "initial.h"

#ifndef LL2_A_BASE
#define LL2_A_BASE 0
#endif

#ifndef LL2_B_BASE
#define LL2_B_BASE 0
#endif

#ifndef LL2_C_BASE
#define LL2_C_BASE 0
#endif

#ifndef COREID
#define COREID DNUM
#endif

extern int GetLogicCoreId(int core_mask, int core_id);
extern int GetCoreNum(int core_mask);
extern void C6678E_SyncN(int core_num, int logic_core_id);
extern void dma_trans(void *src, void *dst, int size);

enum {
  ACTIVATION_NONE = 0,
  ACTIVATION_RELU = 1,
  ACTIVATION_RELU6 = 2
};

enum {
  C6678_SCOPE_DDR = 0,
  C6678_SCOPE_L2 = 1,
  C6678_SCOPE_SMC = 2
};

typedef struct {
  int M;
  int N;
  int K;
  int transpose_a;
  int transpose_b;
  int activation_type;
  int bias_broadcast;
  int a_scope;
  int b_scope;
  int c_scope;
  int block_size;
} C6678MatmulConfig;

static const C6678MatmulConfig kDefaultMatmulConfig = {
  256,
  256,
  256,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  256
};

static inline float apply_activation_none(float value) { return value; }

static inline float apply_activation_relu(float value) {
  return (value > (float)0.0f) ? value : (float)0.0f;
}

static inline float apply_activation_relu6(float value) {
  if (value < (float)0.0f) {
    return (float)0.0f;
  }
  if (value > (float)6.0f) {
    return (float)6.0f;
  }
  return value;
}

static inline float apply_activation(int activation_type, float value) {
  switch (activation_type) {
    case ACTIVATION_RELU:
      return apply_activation_relu(value);
    case ACTIVATION_RELU6:
      return apply_activation_relu6(value);
    case ACTIVATION_NONE:
    default:
      return apply_activation_none(value);
  }
}

static void dma_trans_2d(void *src, void *dst, int acnt, int bcnt, int src_stride, int dst_stride) {
  int row;
  char *src_base = (char *)src;
  char *dst_base = (char *)dst;
  if (acnt <= 0 || bcnt <= 0) {
    return;
  }
  for (row = 0; row < bcnt; ++row) {
    dma_trans(src_base + row * src_stride, dst_base + row * dst_stride, acnt);
  }
}

static void copy_2d_by_scope(const void *src, void *dst, int acnt, int bcnt, int src_stride,
                             int dst_stride, int src_scope, int dst_scope) {
  int row;
  const char *src_base = (const char *)src;
  char *dst_base = (char *)dst;
  if (src_scope == C6678_SCOPE_L2 && dst_scope == C6678_SCOPE_L2) {
    for (row = 0; row < bcnt; ++row) {
      memcpy(dst_base + row * dst_stride, src_base + row * src_stride, acnt);
    }
    return;
  }
  dma_trans_2d((void *)src, dst, acnt, bcnt, src_stride, dst_stride);
}

static void load_row_major_tile(const void *src_base, void *dst, int row0, int col0, int rows,
                                int cols, int src_ld, int elem_size, int src_scope) {
  const char *src = (const char *)src_base + ((row0 * src_ld + col0) * elem_size);
  copy_2d_by_scope(src, dst, cols * elem_size, rows, src_ld * elem_size, cols * elem_size,
                   src_scope, C6678_SCOPE_L2);
}

static void load_transposed_tile(const void *src_base, void *dst, int row0, int col0, int rows,
                                 int cols, int src_ld, int elem_size, int src_scope) {
  int src_row;
  const char *src = (const char *)src_base + ((col0 * src_ld + row0) * elem_size);
  char *dst_base = (char *)dst;
  for (src_row = 0; src_row < cols; ++src_row) {
    copy_2d_by_scope(src + src_row * src_ld * elem_size, dst_base + src_row * elem_size, elem_size,
                     rows, elem_size, cols * elem_size, src_scope, C6678_SCOPE_L2);
  }
}

static void store_row_major_tile(const void *src, void *dst_base, int row0, int col0, int rows,
                                 int cols, int dst_ld, int elem_size, int dst_scope) {
  char *dst = (char *)dst_base + ((row0 * dst_ld + col0) * elem_size);
  copy_2d_by_scope(src, dst, cols * elem_size, rows, cols * elem_size, dst_ld * elem_size,
                   C6678_SCOPE_L2, dst_scope);
}

#define MATMUL_A_VAL(ptr, row, col, M, K, transpose_a) \
  ((ptr)[(transpose_a) ? ((col) * (M) + (row)) : ((row) * (K) + (col))])

#define MATMUL_B_VAL(ptr, row, col, K, N, transpose_b) \
  ((ptr)[(transpose_b) ? ((col) * (K) + (row)) : ((row) * (N) + (col))])

void fp_matmul_fusion_p_(float *A, float *B, float *C, int M, int N, int K,
                                int transpose_a, int transpose_b) {
  int i;
  int j;
  int k;
  for (i = 0; i < M; ++i) {
    for (j = 0; j < N; ++j) {
      float sum = (float)0;
      for (k = 0; k < K; ++k) {
        sum += (float)MATMUL_A_VAL(A, i, k, M, K, transpose_a) *
               (float)MATMUL_B_VAL(B, k, j, K, N, transpose_b);
      }
      C[i * N + j] = (float)(C[i * N + j] + (float)sum);
    }
  }
}

void fp_matmul_fusion_p(float *A, float *B, float *C, float *bias,
                               const C6678MatmulConfig *cfg) {
  int i;
  int j;
  int k;
  for (i = 0; i < cfg->M; ++i) {
    for (j = 0; j < cfg->N; ++j) {
      float sum = (float)0;
      for (k = 0; k < cfg->K; ++k) {
        sum += (float)MATMUL_A_VAL(A, i, k, cfg->M, cfg->K, cfg->transpose_a) *
               (float)MATMUL_B_VAL(B, k, j, cfg->K, cfg->N, cfg->transpose_b);
      }
      float value = (float)sum;
      if (bias != NULL) {
        value = (float)(value + (cfg->bias_broadcast ? bias[j] : bias[i * cfg->N + j]));
      }
      C[i * cfg->N + j] = apply_activation(cfg->activation_type, value);
    }
  }
}

void fp_matmul_fusion_s(float *A, float *B, float *C, float *bias,
                               const C6678MatmulConfig *cfg, int core_mask) {
  int core_num = GetCoreNum(core_mask);
  int core_id = GetLogicCoreId(core_mask, DNUM);
  int rows_per_core;
  int start_row;
  int end_row;
  int i;
  int j;
  int k;
  float *ll2_A;
  float *ll2_B;
  float *ll2_C;
  int a_src_ld = cfg->transpose_a ? cfg->M : cfg->K;
  int b_src_ld = cfg->transpose_b ? cfg->K : cfg->N;

  if (core_num <= 0 || core_id < 0) {
    return;
  }

  rows_per_core = cfg->M / core_num;
  start_row = core_id * rows_per_core;
  end_row = (core_id == core_num - 1) ? cfg->M : (start_row + rows_per_core);

  ll2_A = (float *)LL2_A_BASE;
  ll2_B = (float *)LL2_B_BASE;
  ll2_C = (float *)LL2_C_BASE;

  for (i = start_row; i < end_row; i += cfg->block_size) {
    int current_M = (i + cfg->block_size > end_row) ? (end_row - i) : cfg->block_size;
    for (j = 0; j < cfg->N; j += cfg->block_size) {
      int current_N = (j + cfg->block_size > cfg->N) ? (cfg->N - j) : cfg->block_size;
      memset(ll2_C, 0, current_M * current_N * (int)sizeof(float));
      for (k = 0; k < cfg->K; k += cfg->block_size) {
        int current_K = (k + cfg->block_size > cfg->K) ? (cfg->K - k) : cfg->block_size;
        if (cfg->transpose_a) {
          load_transposed_tile(A, ll2_A, i, k, current_M, current_K, a_src_ld, (int)sizeof(float),
                               cfg->a_scope);
        } else {
          load_row_major_tile(A, ll2_A, i, k, current_M, current_K, a_src_ld, (int)sizeof(float),
                              cfg->a_scope);
        }
        if (cfg->transpose_b) {
          load_transposed_tile(B, ll2_B, k, j, current_K, current_N, b_src_ld, (int)sizeof(float),
                               cfg->b_scope);
        } else {
          load_row_major_tile(B, ll2_B, k, j, current_K, current_N, b_src_ld, (int)sizeof(float),
                              cfg->b_scope);
        }
        fp_matmul_fusion_p_(ll2_A, ll2_B, ll2_C, current_M, current_N, current_K, 0, 0);
      }
      for (k = 0; k < current_M; ++k) {
        int col;
        for (col = 0; col < current_N; ++col) {
          int bias_index = cfg->bias_broadcast ? (j + col) : ((i + k) * cfg->N + j + col);
          float value = ll2_C[k * current_N + col];
          if (bias != NULL) {
            value = (float)(value + bias[bias_index]);
          }
          ll2_C[k * current_N + col] = apply_activation(cfg->activation_type, value);
        }
      }
      store_row_major_tile(ll2_C, C, i, j, current_M, current_N, cfg->N, (int)sizeof(float),
                           cfg->c_scope);
    }
  }

  C6678E_SyncN(core_num, core_id);
}

void fp_matmul_fusion_entry(float *A, float *B, float *C, float *bias,
                                   int core_mask) {
  if (true) {
    fp_matmul_fusion_s(A, B, C, bias, &kDefaultMatmulConfig, core_mask);
  } else {
    (void)core_mask;
    fp_matmul_fusion_p(A, B, C, bias, &kDefaultMatmulConfig);
  }
}
